[toolchain]
anchor_version = "0.32.1"

[features]
resolution = true

[programs.localnet]
solcrush_staking = "2MQaPBWNXRFZS5eb3Tht7GXBgtGvih9L72PNXAmPCRu6"

[programs.devnet]
solcrush_staking = "2MQaPBWNXRFZS5eb3Tht7GXBgtGvih9L72PNXAmPCRu6"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
